version: '3'
services:
  # Application Dockerfile is in same folder which is .
  app:
    build: .
  mysql:
    image: mysql:8.0.15
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

  # db is is db folder
  db:
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always